### get all the users
GET http://localhost:3000/api/users

### get a user
GET http://localhost:3000/api/users/87747103-b5f0-43e8-b52a-9dbf46618676

### get a user
POST http://localhost:3000/api/users/auth
Content-Type: application/json

{
  "id": "41e68118-ad85-45f8-8345-65c58cc878a1",
  "firstname": "MQrdMbhm",
  "lastname": "IsiVoG",
  "password": "password"
}


### add a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "MQrdMbhm",
  "lastName": "IsiVoG",
  "password": "password"
}


### update a user
PUT  http://localhost:3000/api/users/39a6ea3e-c560-4100-9f1a-90c030d11dc7

### gets all the books
GET http://localhost:3000/api/books

### get a book
GET http://localhost:3000/api/books/2179b25e-4bb6-407e-a0d1-b6432206ccb2


### logging
POST  http://localhost:3000/log
Content-Type: application/json

{
    "username":"loda"
}

###
POST  http://localhost:3000/auth
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJzYXJhIiwiaWF0IjoxNjQ3NDQ2NDc2LCJleHAiOjE2NDc0NTAwNzZ9.jB-2625xxyAaTKQoWSQImDHs65w-W48YZNke_QGS75I