###################USERS###################
### get all the users
GET http://localhost:3000/api/users

### get all the users
GET http://localhost:3000/api/users/0164ba30-65d8-4d13-a17d-71bc1d7eb61e


### add a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "khaled",
  "lastName": "mesbah",
  "password": "khalidSF46"
}

### authenticate a user
POST http://localhost:3000/api/users/auth
Content-Type: application/json

{
  "id": "4a8e3cf5-6d17-439a-9048-5039d623464e",
  "firstname": "hager",
  "lastname": "gaber",
  "password": "hagesr"
}


### update a user
PUT  http://localhost:3000/api/users/0164ba30-65d8-4d13-a17d-71bc1d7eb61e
Content-Type: application/json

{
  "firstName": "fasdf",
  "lastName": "mesfsadfbah",
  "password": "soadfa"
}

### logging
POST  http://localhost:3000/log
Content-Type: application/json

{
    "username":"loda"
}

###
POST  http://localhost:3000/auth
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQwYzExOGYtZTc0Ni00OWYxLTk4OWMtYmI2YTdkZWNkODYyIiwiZmlyc3RuYW1lIjoia2hhbGVkIiwibGFzdG5hbWUiOiJtZXNiYWgiLCJwYXNzd29yZCI6IiQyYiQxMCRkdnNIeVpLQ21SQ09YQlcyTW0uMU51STJVblJONHhkS2hscC54VDNWNkJaUnZxRnJVcFFlNiJ9LCJpYXQiOjE2NDc1MjYwNDV9.FOHgjMa2QxAZua9OeQs16AtiUmHc_5nTjTLPMCrPTwc
###
POST  http://localhost:3000/api/users/auth
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQwYzExOGYtZTc0Ni00OWYxLTk4OWMtYmI2YTdkZWNkODYyIiwiZmlyc3RuYW1lIjoia2hhbGVkIiwibGFzdG5hbWUiOiJtZXNiYWgiLCJwYXNzd29yZCI6IiQyYiQxMCRkdnNIeVpLQ21SQ09YQlcyTW0uMU51STJVblJONHhkS2hscC54VDNWNkJaUnZxRnJVcFFlNiJ9LCJpYXQiOjE2NDc1MjYwNDV9.FOHgjMa2QxAZua9OeQs16AtiUmHc_5nTjTLPMCrPTwc




###################PRODUCTS###################
GET http://localhost:3000/api/products