########USERS######USERS########USERS##############USERS######USERS########USERS######
########USERS######USERS########USERS##############USERS######USERS########USERS######
########USERS######USERS########USERS##############USERS######USERS########USERS######
@user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJzX2lkX3BrIjoiZWU4Y2ZkZjEtZWJmNi00NzgzLWE5ZGEtNDJhMmQ2ZDU5NjU2IiwiZmlyc3RfbmFtZSI6IktoYWxpZCIsImxhc3RfbmFtZSI6Ik1lc2JhaCIsInBhc3N3b3JkIjoiJDJiJDEwJGkucUtXaXFTd0xvdzN2M1p5ZndEWGVVVU5kb28yN0RKRkU3RnphYlBvZVV6NlNYVG5NNTZ1In0sImlhdCI6MTY0ODAzOTYyMn0.m2PGQ5Leb4GcwBsWGSIB-c1xTGr06f6dzxNWbBWG7mE
@user_uuid=ee8cfdf1-ebf6-4783-a9da-42a2d6d59656

### get all the users
GET http://localhost:3000/api/users
Authorization: Bearer {{user_token}}

### get a specific user with uuid
GET http://localhost:3000/api/users/{{user_uuid}}
Authorization: Bearer {{user_token}}

### add a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "first_name": "Khalid",
  "last_name": "Mesbah",
  "password": "my_secret_password"
}

### update a user using put request 
PUT  http://localhost:3000/api/users/{{user_uuid}}
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "first_name": "loda",
  "last_name": "sebaq",
  "password": "secret_password"
}

### update a user using patch request 
PATCH http://localhost:3000/api/users/{{user_uuid}}
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "first_name": "Khalid",
  "last_name": "Mesbah",
  "password": "ya"
}

### authenticate a user
GET http://localhost:3000/api/users/auth/{{user_uuid}}
Content-Type: application/json

{
  "password": "my_secret_password"
}

### delete a user
DELETE http://localhost:3000/api/users/{{user_uuid}}
Authorization: Bearer {{user_token}}

########PRODUCTS######PRODUCTS########PRODUCTS##############PRODUCTS######PRODUCTS########PRODUCTS######
########PRODUCTS######PRODUCTS########PRODUCTS##############PRODUCTS######PRODUCTS########PRODUCTS######
########PRODUCTS######PRODUCTS########PRODUCTS##############PRODUCTS######PRODUCTS########PRODUCTS######
@product_uuid=29e4f2ca-d0ba-44b7-875b-ca488a253886
### get all the products => index
GET http://localhost:3000/api/products
Authorization: Bearer {{user_token}}

### get a specific product with uuid => show
GET http://localhost:3000/api/products/{{product_uuid}}
Authorization: Bearer {{user_token}}

### get all products by category
GET http://localhost:3000/api/products/indexByCategory/vegetables
Authorization: Bearer {{user_token}}

### add a product
POST http://localhost:3000/api/products
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "apples",
  "price":115,
  "category":"fruits"
}

### update a product using put http request
PUT http://localhost:3000/api/products/{{product_uuid}}
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "cucamber",
  "price":1152,
  "category":"vegetables"
}

### update a product using patch http request
PATCH http://localhost:3000/api/products/{{product_uuid}}
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "cucamber",
  "price":115,
  "category":"fruits"
}

### delete a product
DELETE http://localhost:3000/api/products/{{product_uuid}}
Authorization: Bearer {{user_token}}

########ORDERS######ORDERS########ORDERS##############ORDERS######ORDERS########ORDERS######
########ORDERS######ORDERS########ORDERS##############ORDERS######ORDERS########ORDERS######
########ORDERS######ORDERS########ORDERS##############ORDERS######ORDERS########ORDERS######

@order_uuid=9b726683-ed16-4ee6-905d-f92e58ca8a60
### get all of the orders
GET http://localhost:3000/api/orders
Authorization: Bearer {{user_token}}

### get a specific order
GET http://localhost:3000/api/orders/{{order_uuid}}
Authorization: Bearer {{user_token}}

### add an order
POST http://localhost:3000/api/orders
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "status": "active",
  "user_id_FK": "{{user_uuid}}"
}

### update a specific order using the patch http request
PATCH  http://localhost:3000/api/orders/{{order_uuid}}
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "status":"complete"
}

### update a specific order using the put http request
PUT  http://localhost:3000/api/orders/{{order_uuid}}
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "status":"active"
}

### add a product to a specific order
POST http://localhost:3000/api/orders/{{order_uuid}}/products
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "quantity": 2222,
  "product_id_FK": "{{product_uuid}}"
}

### get all prodcuts of a specific order 
GET http://localhost:3000/api/orders/{{order_uuid}}/products
Authorization: Bearer {{user_token}}

### delete a specific order
DELETE http://localhost:3000/api/orders/{{order_uuid}}
Authorization: Bearer {{user_token}}

########DASHBOARD######DASHBOARD########DASHBOARD##############DASHBOARD######DASHBOARD########DASHBOARD######
########DASHBOARD######DASHBOARD########DASHBOARD##############DASHBOARD######DASHBOARD########DASHBOARD######
########DASHBOARD######DASHBOARD########DASHBOARD##############DASHBOARD######DASHBOARD########DASHBOARD######

### get all products that have been included in orders
GET http://localhost:3000/api/dashboard/getAllProductsInOrders
Authorization: Bearer {{user_token}}

### get all users that have made orders
GET http://localhost:3000/api/dashboard/getUsersWithOrders
Authorization: Bearer {{user_token}}

### get the <number> most expensive products
GET http://localhost:3000/api/dashboard/getMostExpProducts
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "limit":5
}

### get the most popular products 
GET http://localhost:3000/api/dashboard/getmostPopProducts
Authorization: Bearer {{user_token}}

### get the current order by user 
GET http://localhost:3000/api/dashboard/getCurrentOrderByUser/{{user_uuid}}
Authorization: Bearer {{user_token}}

### get the completed orders by user 
GET http://localhost:3000/api/dashboard/getCompletedOrdersByUser/{{user_uuid}}
Authorization: Bearer {{user_token}}